import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/dashboard/forms');
  await page.getByRole('button', { name: 'Create your first form' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('(formName) field is required').isVisible();
  await page.getByText('(formName) field is required').isVisible();
  await page.getByRole('textbox', { name: 'Flow name*' }).fill('Register test');
  await page.getByRole('textbox', { name: 'Version*' }).fill('1.0.0');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('Please enter at least one form element.').isVisible();
  await page.getByRole('button', { name: 'ShortText' }).click();
  await page.getByRole('button', { name: 'LongText' }).click();
  await page.getByRole('button', { name: 'Email' }).click();
  await page.getByRole('button', { name: 'Number' }).click();
  await page.getByRole('button', { name: 'Dropdown' }).click();
  await page.getByRole('button', { name: 'Signature' }).click();
  await page.getByText('Required').first().click();
  await page.getByText('Required').nth(1).click();
  await page.getByText('Required').nth(3).click();
  await page.getByText('Required').nth(4).click();
  const input = page.getByPlaceholder('New option...').first();
  await input.fill('Male');
  await input.press('Enter');
  await input.fill('Female');
  await input.press('Enter');
  await page.getByRole('button', { name: 'ShortText' }).click();
  await page.getByRole('button', { name: 'LongText' }).click();
  await page.getByRole('button', { name: 'Email' }).click();
  await page.getByRole('button', { name: 'Number' }).click();
  await page.getByRole('button', { name: 'Dropdown' }).click();
  await page.getByRole('button', { name: 'Signature' }).click();
  await page.getByText('Required').nth(6).click();
  await page.getByText('Required').nth(7).click();
  await page.getByText('Required').nth(9).click();
  await page.getByRole('button', { name: 'Client' }).nth(6).click();
  await page.getByRole('button', { name: 'Client' }).nth(7).click();
  await page.getByRole('button', { name: 'Client' }).nth(8).click();
  await page.getByRole('button', { name: 'Client' }).nth(9).click();
  await page.getByRole('button', { name: 'Client' }).nth(10).click();
  await page.getByRole('button', { name: 'Client' }).nth(11).click();

  const input2 = page.getByPlaceholder('New option...').nth(1);
  await input2.fill('Apple');
  await input2.press('Enter');
  await input2.fill('Orange');
  await input2.press('Enter');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.waitForURL('**/dashboard/forms');
  await expect(page).toHaveURL(/\/dashboard\/forms$/);
  await expect(page.getByText('Form created successfully.')).toBeVisible();
  await page.getByRole('button', { name: 'Create Submission' }).click();
  await expect(page).toHaveURL(/\/dashboard\/forms\/[^/]+\/create$/);
  await expect(page.getByText('Register test')).toBeVisible();
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByText('(ShortText) field is required')).toBeVisible();
  await expect(page.getByText('(LongText) field is required')).toBeVisible();
  await expect(page.getByText('(Email) field is required')).toBeVisible();
  await expect(page.getByText('(Number) field is required')).toBeVisible();
  await expect(page.getByText('(Dropdown) field is required')).toBeVisible();
  await expect(page.getByText('(Signature) field is required')).toBeVisible();
  await expect(page.getByLabel('ShortText').first()).not.toBeDisabled();
  await expect(page.getByLabel('LongText').first()).not.toBeDisabled();
  await expect(page.getByLabel('Email').first()).not.toBeDisabled();
  await expect(page.getByLabel('Number').first()).not.toBeDisabled();
  await expect(page.getByLabel('Dropdown').first()).not.toBeDisabled();
  const deleteIcon = page.locator('app-signature-pad mat-icon', { hasText: 'delete' }).first();
  await expect(deleteIcon).toBeVisible();
  await expect(page.getByLabel('ShortText').last()).toBeDisabled();
  await expect(page.getByLabel('LongText').last()).toBeDisabled();
  await expect(page.getByLabel('Email').last()).toBeDisabled();
  await expect(page.getByLabel('Number').last()).toBeDisabled();
  await expect(page.getByLabel('Dropdown').last()).toBeDisabled();
  await page.getByText('Flows').click();
  await expect(page).toHaveURL(/\/dashboard\/forms$/);
  await page.locator('mat-icon', { hasText: 'delete' }).click();
  await page.getByRole('button', { name: 'delete' }).click();
  await expect(page.getByText('Form deleted successfully.')).toBeVisible();
});
